# Generated by Django 2.2.5 on 2021-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_with_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=255)),
                ('expert_email', models.EmailField(max_length=254)),
                ('expert_phone_number', models.CharField(max_length=12)),
                ('resume_url', models.FileField(upload_to='media/resume/')),
                ('background', models.FileField(upload_to='media/background/')),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
