# Generated by Django 2.2.5 on 2021-02-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210220_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_withuss',
            new_name='careers',
        ),
    ]
