# Generated by Django 2.2.5 on 2021-02-21 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_auto_20210220_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=400)),
                ('slot', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
