# Generated by Django 2.2.5 on 2021-02-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210221_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech_support',
            old_name='user',
            new_name='username',
        ),
    ]
