# Generated by Django 2.2.5 on 2021-02-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210221_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech_support',
            old_name='username',
            new_name='user_name',
        ),
    ]
