# Generated by Django 2.2.5 on 2021-02-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_auto_20210221_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_support1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('query', models.TextField(max_length=400)),
                ('slot', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tech_support',
            name='user_name',
        ),
        migrations.AddField(
            model_name='tech_support',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tech_support', to=settings.AUTH_USER_MODEL),
        ),
    ]
