# Generated by Django 3.0.6 on 2021-02-22 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_auto_20210222_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='telephone_tech_support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('slot', models.CharField(max_length=160)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telephone_tech_support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tech_support',
            name='user',
        ),
        migrations.DeleteModel(
            name='tech_support1',
        ),
        migrations.DeleteModel(
            name='tech_support',
        ),
    ]
