# Generated by Django 3.0.6 on 2021-02-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_one_on_one_online_session_video_tech_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='online_group_discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('slot', models.CharField(max_length=160)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='online_group_discussion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
