# Generated by Django 3.0.6 on 2021-02-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_online_group_discussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answerpage', models.TextField()),
            ],
        ),
    ]
