# Generated by Django 3.0.6 on 2021-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_querypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer_heading', models.TextField()),
                ('youtube_link', models.CharField(max_length=255)),
                ('article_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='QueryPage',
        ),
    ]
